version: 2024/05/09
# IMAP settings
IMAP_SERVER: <exchange.server>
IMAP_USERNAME: <AD>
IMAP_PASSWORD: <Password>

# Jira settings
JIRA_URL: <https://tool-dev.home/jira>
JIRA_USERNAME: <AD>
JIRA_PASSWORD: <Password>
JIRA_PROJECT_KEY: I4

# Mailbox paths
INBOX_PATH: inbox/test/ingest
COMPLETED_PATH: inbox/test/completed
ERROR_PATH: inbox/test/error

# Rmail content to Jira
TEXT2JIRA:
  Issue_Type:
    FIELD: issuetype
  Description:
    FIELD: description
  Components(External_Events_Webinars/Regular_Task/Work_Progress):
    FIELD: components
    DEFAULT: Regular_Task
  Labels(PMO/VMO/RMS/KITEC_Relocation/Planning/Security_Awareness/IT_Mgmt/T&D/Cybersecurity_Awareness/Events):
    FIELD: labels
    DEFAULT: PMO
  Start_Date(DD/MMM/YYYY):
    FIELD: customfield_10603
  Due_Date(DD/MMM/YYYY):
    FIELD: duedate
  Actutal_End_Date(DD/MMM/YYYY):
    FIELD: customfield_10418
  Priority(Low/Medium/High/Urgent):
    FIELD: priority
    DEFAULT: Low
  Release_Notes:
    FIELD: customfield_11824
  Assignee(LWH201/TWH327/Lck599/LDD298):
    FIELD: assignee
  Reporter:
    FIELD: reporter
    DEFAULT: Lck599

LOGGING:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: "[%(asctime)s] %(name)s - %(levelname)s - %(message)s  (line:%(lineno)s in %(funcName)s)"
      datefmt: "%Y-%m-%d %H:%M:%S%z"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout

    file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: simple
      filename: ./log/info.log
      maxBytes: 20971520 # 20MB
      backupCount: 2
      encoding: utf8

  loggers:
    email2jira:
      level: DEBUG
      handlers: [console, file_handler]
      propagate: no

  root:
    level: DEBUG
    handlers: [console, file_handler]
